# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
       end
    end
  end
end

target 'TCDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TCDemo

  pod 'PKHUD'
  pod 'Alamofire', '~> 4.9.1'
  pod 'IGListKit'
  pod 'SDWebImage'
  pod 'lottie-ios', '~> 3.2.1'
  pod 'SnapKit'
  pod 'Giphy', '~> 1.3.0'
  pod 'WCDB.swift'
  pod 'HyphenateChat', '4.0.0'
  pod 'EMVoiceConvert'
  pod 'MJRefresh'
  pod 'FMDB'
  pod 'AWSS3'
  pod "youtube-ios-player-helper"

end
